### PR TITLE
Add Discovery API Heatmap to the website

### PR DESCRIPTION
**Pull request by aslight21**
Add Discovery Heatmap article to partners/startups-and-developpers

### CODE REVIEW

**Comment by aslight21** [comment]
We also wanted to add a tag heatmap in Startups & Developers, but just adding the tag in the article md file seems not to be enough. The behavior was buggy. So this pull request don't have the tag heatmap, but if you help us with that we can add it later.

**Comment by degratnik** [comment]
Hi, I will review and merge it ASAP.

**Comment by degratnik** [comment]
Could you describe buggy behavior with new tag?

**Comment by aslight21** [comment]
Thanks for the quick merge !

For the bug, Its probably us that don't understand very well the integration of the tags, but if we had a tag heatmap under web in heatmap.md:

image

We then see the the tag on the site and he seems to work well:
image

The bug is when we click on the "web" sub-menu after clicking the "heatmap" sub-menu, the button works but the "heatmap" sub-menu still highlight : 

image

If we scroll up, the side-menu seems to refresh to the correct state.

Also, if we had the "heatmap" sub-menu in the expanded-menu-header, the click on "heatmap" or "web" redirect to the right url :  .../partners/startups-and-developers/#heatmap

However the tag "heatmap" don't activate. The startups and developers section still show article without the tag "heatmap" and this tag isn't activated under the article.

Maybe it's the way it's supposed to work or maybe we need to had a line or two of code somewhere, but we don't know where it would be.

I will create a new merge request for you to see the behavior by yourself.

**Pull request merged**
